import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {

  const user = useUser();

  const {data} = api.post.getLatest.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="bg-custom-blue fixed right-0 top-0 rounded-bl-lg p-2 font-mono font-semibold text-white hover:bg-cyan-600">
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
        {data?.map(({ id, content }) => <div key={id}>{content}</div>)}
      </main>
    </>
  );
}
